-- Seed data for Tennis Scheduler application
-- This file seeds the courts table with initial data

-- Insert courts data
INSERT INTO public.courts (
  id,
  name,
  address,
  city,
  state,
  zip_code,
  latitude,
  longitude,
  peak_price,
  off_peak_price,
  surface,
  rating,
  review_count,
  total_courts,
  description,
  images,
  amenities,
  available_days
) VALUES
(
  '1',
  'Crandon Park Tennis Center',
  '7300 Crandon Blvd',
  'Key Biscayne',
  'FL',
  '33149',
  25.6925,
  -80.1556,
  25,
  15,
  'Hard',
  4.8,
  342,
  13,
  'Premier public tennis facility in Key Biscayne. Home to the Miami Open, featuring 13 hard courts with professional lighting. Beautiful ocean views and well-maintained facilities.',
  '["/court1.jpg"]'::jsonb,
  '["Lights", "Parking", "Restrooms", "Water Fountains", "Pro Shop"]'::jsonb,
  '["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"]'::jsonb
),
(
  '2',
  'Flamingo Park Tennis Center',
  '1000 12th St',
  'Miami Beach',
  'FL',
  '33139',
  25.7906,
  -80.1300,
  20,
  12,
  'Hard',
  4.7,
  289,
  19,
  'Popular public tennis center in the heart of Miami Beach. 19 well-maintained hard courts with excellent lighting for evening play. Great community atmosphere.',
  '["/court2.jpg"]'::jsonb,
  '["Lights", "Parking", "Restrooms", "Water Fountains", "Seating Area"]'::jsonb,
  '["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"]'::jsonb
),
(
  '3',
  'Tampa Bay Park Tennis Courts',
  '400 N Ashley Dr',
  'Tampa',
  'FL',
  '33602',
  27.9506,
  -82.4572,
  18,
  10,
  'Hard',
  4.6,
  198,
  8,
  'Scenic public tennis facility along the Hillsborough River. 8 hard courts with beautiful waterfront views. Perfect for recreational play with family and friends.',
  '["/court3.jpg"]'::jsonb,
  '["Lights", "Parking", "Restrooms", "Water Fountains"]'::jsonb,
  '["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"]'::jsonb
),
(
  '4',
  'Lake Cane Tennis Center',
  '8495 Turkey Lake Rd',
  'Orlando',
  'FL',
  '32819',
  28.4500,
  -81.4700,
  22,
  14,
  'Clay',
  4.9,
  267,
  12,
  'Premier public clay court facility in Orlando. 12 professional-grade clay courts with excellent drainage. Perfect for players who prefer the slower pace and softer surface of clay.',
  '["/court4.jpg"]'::jsonb,
  '["Lights", "Parking", "Restrooms", "Water Fountains", "Pro Shop"]'::jsonb,
  '["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"]'::jsonb
),
(
  '5',
  'Holiday Park Tennis Center',
  '701 NE 12th Ave',
  'Fort Lauderdale',
  'FL',
  '33304',
  26.1224,
  -80.1374,
  20,
  12,
  'Hard',
  4.5,
  312,
  18,
  'Historic public tennis facility in Fort Lauderdale. 18 hard courts with excellent lighting. Popular destination for both locals and visitors. Great community atmosphere.',
  '["/court5.jpg"]'::jsonb,
  '["Lights", "Parking", "Restrooms", "Water Fountains", "Seating Area"]'::jsonb,
  '["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"]'::jsonb
)
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  address = EXCLUDED.address,
  city = EXCLUDED.city,
  state = EXCLUDED.state,
  zip_code = EXCLUDED.zip_code,
  latitude = EXCLUDED.latitude,
  longitude = EXCLUDED.longitude,
  peak_price = EXCLUDED.peak_price,
  off_peak_price = EXCLUDED.off_peak_price,
  surface = EXCLUDED.surface,
  rating = EXCLUDED.rating,
  review_count = EXCLUDED.review_count,
  total_courts = EXCLUDED.total_courts,
  description = EXCLUDED.description,
  images = EXCLUDED.images,
  amenities = EXCLUDED.amenities,
  available_days = EXCLUDED.available_days,
  updated_at = NOW();

